version: '3.4'

services:
  ctesifonte.sqlserver:
    container_name: ctesifonteMSSQL
    environment:
      - MSSQL_SA_PASSWORD=Abc@1234
      - ACCEPT_EULA=Y
    ports:
      - "1400:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  ctesifonte.mordor:
    container_name: ctesifonteMordor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=3443
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "81:80"
      - "3443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ctesifonte.hefestos:
    container_name: ctesifonteHefestos
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=3445
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "82"
      - "3445:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ctesifonte.hades:
    container_name: ctesifonteHades
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=3444
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "80"
      - "3444:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro